**QUESTION-1** How to Creating a 3x3 Identity Matrix with Float Data Type?

In [ ]:
import numpy as np

In [ ]:
arr = np.identity(3, dtype=float)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr.dtype

dtype('float64')

**QUESTION-2**  Create a 1D Array with Random Values between 0 and 1.


In [ ]:
arr1 = np.random.rand(10)
arr1

array([0.05479062, 0.82608194, 0.45889976, 0.61514657, 0.02153697,
       0.80710216, 0.42883769, 0.99514126, 0.43792366, 0.96138769])

**QUESTION-3**  Create a 2D Array with Random Integer Values.

In [ ]:
arr2 = np.random.randint(10, size=(2,5))
arr2


array([[4, 0, 1, 9, 0],
       [0, 8, 6, 4, 5]])

QUESTION-4    Creating an Array Using a Custom Function.

**QUESTION-5**  Reshaping a 1D Array into a 2D Array

In [ ]:
arr = np.arange(9)
print("1-D Array")
print(arr)

arr1 = arr.reshape(3,3)
print("\nReshaping 1-D Array into 2-D Array")
arr1

1-D Array
[0 1 2 3 4 5 6 7 8]

Reshaping 1-D Array into 2-D Array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**QUESTION-6** How to Creating a 3x3 Array of Ones?

In [ ]:
arr = np.ones((3,3), dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

**QUESTION-7** How to get the common items between two pythons
NumPy? Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
Expected Output:
array ([2, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)


[2 4]


QUESTION-8  From array a remove all items present in
array b Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
Expected Output:
array ([1,2,3,4]

In [ ]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


QUESTION-9 Limit the number of items printed in python NumPy array a to a maximum of
6 elements.
a = np. arrange (15)
Expected Output:
array ([ 0, 1, 2, ..., 12, 13, 14]

In [ ]:
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


**QUESTION-10**  Drop all nan values from a 1D NumPy
array Input:
np. array ([1,2,3, np.nan,5,6,7, np.nan])
Desired Output:
array ([ 1., 2., 3., 5., 6., 7.])

In [ ]:
arr = np.array([1,2,3, np.nan,5,6,7, np.nan])
print(arr)

arr1 = arr[~np.isnan(arr)]
print(arr1)

[ 1.  2.  3. ...  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


**QUESTION-11**  Create a 1D NumPy array of the first 20 natural numbers and a
2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [ ]:
arr1 = np.arange(20)
print(arr1)

arr2 = np.arange(1,21).reshape(4,5)
print(arr2)

[ 0  1  2 ... 17 18 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**QUESTION-12**  Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
number of dimensions, and data type. Change its data type to float64 and verify
the change.

In [ ]:
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
arr1 = arr.astype(np.float64)
arr1.dtype

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
24
3
int64


dtype('float64')

 **QUESTION-13** : Reshape a 1D array of 12 elements into a 3x4 2D array and then
flatten it back into a 1D array using ravel (). Verify that the flattened array
matches the original.

In [ ]:
arr = np.arange(12)
print(arr)
arr1 = arr.reshape(3,4)
print(arr1)

[ 0  1  2 ...  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**QUESTION-14**  Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division. Explain the behavior when dividing by zero.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

c = np.array([0,0,0])
print(a/c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[inf inf inf]


/tmp/ipython-input-2331356418.py:9: RuntimeWarning: divide by zero encountered in divide
  print(a/c)


**QUESTION-15**  Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
element-wise addition using broadcasting. Explain how broadcasting rules apply
in this scenario.

In [ ]:
a = np.arange(3).reshape(3,1)
print("array a : ")
print(a)
print()

b = np.arange(3)
print("array b :")
print(b)
print()

print("Addition of a and b :")
print(a+b)
print()

print(" a has shape (3, 1) → a column vector\n b has shape (1,3) → a row vector\n a is broadcast across columns\n b is broadcast across rows\n So, the result shape becomes (3, 3) and the operation happens element-wise ")

array a : 
[[0]
 [1]
 [2]]

array b :
[0 1 2]

Addition of a and b :
[[0 1 2]
 [1 2 3]
 [2 3 4]]

 a has shape (3, 1) → a column vector
 b has shape (1,3) → a row vector
 a is broadcast across columns
 b is broadcast across rows
 So, the result shape becomes (3, 3) and the operation happens element-wise 


**QUESTION-16**  Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

In [ ]:
arr = np.random.randint(0,10, size=(4,5))
print(arr)
print()

mask = arr > 5
print(mask)
print()

arr[mask] = 5
print(arr)

[[6 8 4 2 9]
 [6 6 3 6 1]
 [6 0 5 7 6]
 [9 9 6 8 8]]

[[ True  True False False  True]
 [ True  True False  True False]
 [ True False False  True  True]
 [ True  True  True  True  True]]

[[5 5 4 2 5]
 [5 5 3 5 1]
 [5 0 5 5 5]
 [5 5 5 5 5]]


**QUESTION-17**  Given a 4x4 array of random integers, use indexing and slicing
to extract:

o The entire second row

o The last column

o The subarray consisting of the first two rows and first two columns

In [ ]:
arr = np.random.randint(16, size=(4,4))
print(arr)
print()

print(arr[1])
print()


print(arr[:,-1])
print()

print(arr[0:2,0:2])


[[10 14  5  6]
 [ 0 11 10 10]
 [15 12 10  0]
 [10  4 12 11]]

[ 0 11 10 10]

[ 6 10  0 11]

[[10 14]
 [ 0 11]]


**QUESTION-18**  Describe a practical example where NumPy can be used in EDA,
AI, ML, and DL, and implement a NumPy solution for a simple task in each
area.

In [ ]:
print("EDA practical use is Data cleaning, statistical summaries, outlier detection\nand role of NumPy is Fast array manipulation and statistics")
print()
import numpy as np

# Students ke marks (out of 100)
marks = np.array([45, 50, 55, 60, 65, 70, 95])  # 95 thoda high lag raha hai

# Mean (average)
mean = np.mean(marks)

# Median (middle value)
median = np.median(marks)

# Outliers: agar marks mean se 20 se zyada door ho, to outlier
outliers = marks[np.abs(marks - mean) > 20]

print("Marks:", marks)
print("Mean:", mean)
print("Median:", median)
print("Outliers:", outliers)


EDA practical use is Data cleaning, statistical summaries, outlier detection
and role of NumPy is Fast array manipulation and statistics

Marks: [45 50 55 ... 65 70 95]
Mean: 62.857142857142854
Median: 60.0
Outliers: [95]


In [ ]:
print("AI practical use in Rule-based systems or logic programming\nand role of NumPy is Efficient condition checking and scoring ")
print()

temps = np.array([30, 45, 60, 80, 100])

# Rule: if temp > 75 → "High", else "Normal"
status = np.where(temps > 75, "High", "Normal")

print("Temperature status:", status)

AI practical use in Rule-based systems or logic programming
and role of NumPy is Efficient condition checking and scoring 

Temperature status: ['Normal' 'Normal' 'Normal' 'High' 'High']


In [ ]:
print("ML practical use is Data preprocessing, feature scaling, gradient computation\nand role of NumPy is Vectorized operations for speed")
print()
data = np.array([[50, 200], [30, 100], [20, 80], [70, 300]])
min_vals = data.min(axis=0)
max_vals = data.max(axis=0)

normalized = (data - min_vals) / (max_vals - min_vals)
print("Normalized data:\n", normalized)

ML practical use is Data preprocessing, feature scaling, gradient computation
and role of NumPy is Vectorized operations for speed

Normalized data:
 [[0.6        0.54545455]
 [0.2        0.09090909]
 [0.         0.        ]
 [1.         1.        ]]


In [ ]:
print("DL practical use is Tensor operations, forward propagation\nand NumPy underpins many frameworks (e.g., TensorFlow, PyTorch)")
print()
# Inputs (4 features), weights (4x3 for 3 neurons), biases
inputs = np.array([1.0, 2.0, 3.0, 2.5])
weights = np.array([[0.2, 0.8, -0.5],
                    [0.5, -0.91, 0.26],
                    [-0.26, -0.27, 0.17],
                    [0.1, 0.14, 0.5]])
biases = np.array([2, 3, 0.5])

# Forward pass
output = np.dot(inputs, weights) + biases

# ReLU activation
relu_output = np.maximum(0, output)

print("Output after ReLU:", relu_output)



DL practical use is Tensor operations, forward propagation
and NumPy underpins many frameworks (e.g., TensorFlow, PyTorch)

Output after ReLU: [2.67 1.52 2.28]


**QUESTION-19**  Create a random 4x4 matrix and use NumPy to compute its
eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the
matrix.

In [ ]:
import numpy as np

# Step 1: Create a random 4x4 matrix
np.random.seed(0)  # for reproducibility
A = np.random.rand(4, 4)
print("Original matrix A:\n", A)

# Step 2: Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)

# Step 3: Reconstruct the matrix A using eigen decomposition
# A ≈ V @ D @ V_inv
V = eigenvectors
D = np.diag(eigenvalues)
V_inv = np.linalg.inv(V)

A_reconstructed = V @ D @ V_inv
print("\nReconstructed A (from eigen decomposition):\n", A_reconstructed)

# Step 4: Verify reconstruction
is_close = np.allclose(A, A_reconstructed)
print("\nDo the original and reconstructed matrices match (within tolerance)?", is_close)


Original matrix A:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Eigenvalues:
 [ 2.28158836 -0.5139378  -0.22422772  0.53013911]

Eigenvectors (columns):
 [[ 0.52354106 -0.10090767  0.5285094  -0.1584302 ]
 [ 0.49196427  0.55773542 -0.43250014  0.36386336]
 [ 0.59384504  0.23102177 -0.57357157 -0.81262442]
 [ 0.36224851 -0.79080831  0.45236832  0.42678435]]

Reconstructed A (from eigen decomposition):
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]

Do the original and reconstructed matrices match (within tolerance)? True


**QUESTION-20** Create a 1D array of 27 elements and reshape it into a 3x3x3
3D array. Flatten it back into a 1D array and compare the flattened array
with the original.

In [ ]:
arr = np.arange(27)
print(arr)
print()

arr = np.arange(27).reshape(3,3,3)
print(arr)
print()

arr1 = arr.flatten()
print(arr1)

[ 0  1  2 ... 24 25 26]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[ 0  1  2 ... 24 25 26]


**QUESTION-21**  Perform matrix multiplication of two 2D arrays using np.dot ()
and @. Compare the results and performance of both methods using a large
dataset.

In [ ]:
arr1 = np.random.randint(1000, size=(100,100))
arr2 = np.random.randint(1000, size=(100,100))

arr3 = np.dot(arr1,arr2)
print(arr3)
print()

arr4 = arr1 @ arr2
print(arr4)

result = np.allclose(arr3, arr4)
print("Both are same",result)


[[27233270 25494729 24632980 ... 23737446 23606527 24391439]
 [29920760 27324942 27389970 ... 27551714 26814102 27467875]
 [24119518 23243486 23353880 ... 25707838 23063734 23800336]
 ...
 [25450667 25358828 26986815 ... 24822578 24363106 23973144]
 [23768948 24261376 23430155 ... 25324127 22283330 23179952]
 [24334999 22375702 23862427 ... 23885220 22069290 22260708]]

[[27233270 25494729 24632980 ... 23737446 23606527 24391439]
 [29920760 27324942 27389970 ... 27551714 26814102 27467875]
 [24119518 23243486 23353880 ... 25707838 23063734 23800336]
 ...
 [25450667 25358828 26986815 ... 24822578 24363106 23973144]
 [23768948 24261376 23430155 ... 25324127 22283330 23179952]
 [24334999 22375702 23862427 ... 23885220 22069290 22260708]]
Both are same True


**QUESTION-22**  Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,
1). Perform an element-wise operation using broadcasting and explain the
result. Use np. new axis to achieve the same result without broadcasting.

In [ ]:
a = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]])
b = np.array([[3],[4],[6],[7]])
result = a + b
print(result)
print()

print("a ->(2,1,4)\nb->(4,1)\nNumPy adds 1s in missing dimensions to the left of b\nso b->(1,4,1\nresult is (2,4,4))")

[[[ 4  5  6  7]
  [ 5  6  7  8]
  [ 7  8  9 10]
  [ 8  9 10 11]]

 [[ 8  9 10 11]
  [ 9 10 11 12]
  [11 12 13 14]
  [12 13 14 15]]]

a ->(2,1,4)
b->(4,1)
NumPy adds 1s in missing dimensions to the left of b
so b->(1,4,1
result is (2,4,4))


**QUESTION-23** Generate a 2D array of random floats between 0 and 1. Use
conditional operators to create a Boolean mask for values less than 0.5.
Replace these values with their squares and leave the rest unchanged

In [ ]:
arr = np.random.rand(3,4)
print(arr)
print()
mask = arr < 0.5
arr[mask] = arr[mask]**2
print(arr)

[[0.05358289 0.44921315 0.85424264 0.89076144]
 [0.14802146 0.93280417 0.16500071 0.59241163]
 [0.86257845 0.70482209 0.27492754 0.11386076]]

[[0.00287113 0.20179246 0.85424264 0.89076144]
 [0.02191035 0.93280417 0.02722523 0.59241163]
 [0.86257845 0.70482209 0.07558515 0.01296427]]


**QUESTION-24**  Given a 5x5 array of sequential integers, use slicing to:

o Extract the diagonal elements

o Replace the elements of the middle row with zeros

o Flip the array vertically and horizontally

In [ ]:
arr = np.arange(25).reshape(5,5)
print(arr)
print()

d = arr.diagonal()
print(d)
print()

arr[2, :]=0
print(arr)
print()

vertical_flip = np.fliplr(arr)
print(vertical_flip)
print()

horizontal_flip = np.flipud(arr)
print(horizontal_flip)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]
 [24 23 22 21 20]]

[[20 21 22 23 24]
 [15 16 17 18 19]
 [ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


**QUESTION-25**  Create a 4D array of shape (2, 3, 4, 5) with random integers.
Use advanced slicing to extract a subarray and compute the mean along a
specified axis.

In [ ]:
arr = np.random.randint(0,100, size=(2,3,4,5))
print(arr)
print()

subarray = arr[0, 1:, :2, :]
print(subarray.shape)
print()

mean_result = np.mean(subarray, axis=2)
print(mean_result)
print(mean_result.shape)

[[[[27 72 59  2 77]
   [34 73 42 21 86]
   [59 93 75 25 68]
   [73 66 40 16  8]]

  [[29 83 51 93  6]
   [57 38 12 45  7]
   [71 19  8  0 10]
   [88 82 38 49 49]]

  [[71 31 94  8 74]
   [81 83 27 25 84]
   [47 54 75 27  5]
   [38 73 39 94 34]]]


 [[[81 54 11  2 32]
   [39 51 73 98 10]
   [25 87 54 95 51]
   [77 71 41 37 69]]

  [[76 92  3 70 43]
   [46 62 70  4 28]
   [36 23 31 91 91]
   [ 4 50 17 17 62]]

  [[51 58 21 94 77]
   [21 62 70 75  9]
   [76  0 32 36 53]
   [23 48 51 24 94]]]]

(2, 2, 5)

[[52.4 31.8]
 [55.6 60. ]]
(2, 2)


**QUESTION-26**  Given an array of shape (10, 20), reshape it to (20, 10) and (5,
40). Discuss the impact on the array's shape, size, and dimensionality.

In [ ]:
arr1 = np.arange(200).reshape(10,20)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print()

arr2 = np.arange(200).reshape(20,10)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print()

arr3 = np.arange(200).reshape(5,40)
print(arr3.shape)
print(arr3.size)
print(arr3.ndim)
print()


(10, 20)
200
2

(20, 10)
200
2

(5, 40)
200
2



**QUESTION-27**  Generate a large 2D array and demonstrate the use of np. reshape
() and unravel () to manipulate its shape for various linear algebra operations.

In [ ]:
arr = np.arange(1000)
print(arr)
print()

arr1 = arr.reshape(10,100)
print(arr1)
print()

arr2 = arr.ravel()
print(arr2)
print()

[  0   1   2 ... 997 998 999]

[[  0   1   2 ...  97  98  99]
 [100 101 102 ... 197 198 199]
 [200 201 202 ... 297 298 299]
 ...
 [700 701 702 ... 797 798 799]
 [800 801 802 ... 897 898 899]
 [900 901 902 ... 997 998 999]]

[  0   1   2 ... 997 998 999]



**QUESTION-28**  Given a 6x6 matrix, use advanced indexing and slicing to extract
the upper triangular part of the matrix and set the lower triangular part to zero.
Verify the result.

In [ ]:
matrix = np.random.randint(1, 100, size=(6, 6))
print(matrix)
print()

upper_tri = np.triu(matrix)
print(upper_tri)
print()

is_lower_zero = np.allclose(np.tril(matrix, -1), 0)
print(is_lower_zero)

[[35 93 98 14  5 54]
 [27 55 77 63 46 10]
 [56 70 45 54 10 74]
 [26  3 46  5 46 98]
 [70 68  6  4 12 75]
 [16 50 64 77 50 22]]

[[35 93 98 14  5 54]
 [ 0 55 77 63 46 10]
 [ 0  0 45 54 10 74]
 [ 0  0  0  5 46 98]
 [ 0  0  0  0 12 75]
 [ 0  0  0  0  0 22]]

False
